version: "3.5"

services:
  postgres:
    image: postgres:9.5
    networks:
      - postgres_net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      - ./data/postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  postgres_net:
    driver: bridge
